### PR TITLE
Near ideal barrel rolling checks

### LINKED ISSUE #1: Barrel roll might trigger if you have variables 'barrel' and 'roll' used in line, which also has a comment
https://github.com/Qubus0/DoABarrelRoll/blob/d171245c980cf5aa34c5da8ca4fc2114dd8b4194/addons/DoABarrelRoll/DoABarrelRoll.gd#L62

It's definitely a very serious issue that needs to be fixed and not just a joke
You see, words 'barrel' and 'roll' are very common and I'm confident that people always use them in their game logic, but combining them in one line, which also ontains a comment, would trigger a barrel roll

Very very realistic example which I have found in production code and not just wrote a second ago:
```
funс fibonacci(first, roll):
  var barrel = first + roll # next fibonacci number
  print(barrel)
  fibonacci(roll, barrel) # it even happens twice in this function!!1!
```

### PR DESCRIPTION
**Pull request by shyperson0**
Only consider comment lines as barrel rollable, make sure "barrel" and "roll" are written one after another, and convert line to lower case before using it to allow Capitalized or ALL CAPS lines to roll too.

Also addresses #1 since lines with code are excluded.

### CODE REVIEW

**Review by Qubus0 — COMMENTED** [review]
nice, looks good, thank you :)
Could you update the usage hint in the readme as well?

**Comment by shyperson0** [comment]
That should do it. Thank **you**.

**Review by Qubus0 — APPROVED** [review]
prefect, thanks :)

**Comment by VladoCC** [comment]
Why only comment lines? I think splitting line by first "#" character would allow for lines with code to work too
Would be a cool improvement

**Pull request merged**
